[package]
name = "hello_world"
version = "0.1.0"
authors = ["Josh Thomas <josh@ionic.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.9.11"